### ISSUE TITLE
` .github/release-drafter.yml` not included in `push` workflow

### ISSUE THREAD

**Issue by adehad** [ansible-community/devtools#17]
This causes the [release-drafter workflow](https://github.com/marketplace/actions/release-drafter) to fail if the repo doesn't have the `release-drafter.yml` config associated with it already.

e.g. https://github.com/pycontribs/jira/runs/4345876044?check_suite_focus=true

Perhaps we can add a line to the build config that downloads this repo's one if not present:

```yaml
jobs:
  update_release_draft:
    runs-on: ubuntu-20.04
    steps:
      - name: Verify template exists if not use our default
        run: test -f .github/release-drafter.yml || curl https://github.com/ansible-community/devtools/blob/main/.github/release-drafter.yml > .github/release-drafter.yml
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
